"""
Base Agent Architecture for Agentic RAG System
Implements specialized agents for different query types and tasks
"""
import logging
from abc import ABC, abstractmethod
from typing import Dict, List, Any, Optional, Tuple
from dataclasses import dataclass
from enum import Enum
import json
import re

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class AgentType(Enum):
    QUERY_ANALYZER = "query_analyzer"
    SCHEMA_AGENT = "schema_agent"
    SQL_AGENT = "sql_agent"
    TEXT_AGENT = "text_agent"
    SYNTHESIS_AGENT = "synthesis_agent"

@dataclass
class AgentMessage:
    """Message structure for agent communication"""
    sender: str
    receiver: str
    message_type: str
    content: Dict[str, Any]
    timestamp: float
    metadata: Optional[Dict[str, Any]] = None

@dataclass
class QueryPlan:
    """Query execution plan generated by agents"""
    query_id: str
    original_query: str
    query_type: str  # 'simple_sql', 'complex_hybrid', 'text_only'
    steps: List[Dict[str, Any]]
    required_agents: List[AgentType]
    estimated_complexity: int
    context_requirements: Dict[str, Any]

@dataclass
class AgentResponse:
    """Response structure from agents"""
    agent_type: AgentType
    success: bool
    content: Any
    confidence: float
    execution_time: float
    metadata: Dict[str, Any]
    error_message: Optional[str] = None

class BaseAgent(ABC):
    """Abstract base class for all RAG agents"""
    
    def __init__(self, agent_type: AgentType, config: Dict[str, Any] = None):
        self.agent_type = agent_type
        self.config = config or {}
        self.logger = logging.getLogger(f"{self.__class__.__name__}")
        
        # Agent capabilities and limitations
        self.capabilities = self._define_capabilities()
        self.limitations = self._define_limitations()
        
        # Performance tracking
        self.execution_stats = {
            "total_queries": 0,
            "successful_queries": 0,
            "average_response_time": 0.0,
            "error_count": 0
        }
        
        self.logger.info(f"Initialized {self.agent_type.value} agent")
    
    @abstractmethod
    def _define_capabilities(self) -> List[str]:
        """Define what this agent can do"""
        pass
    
    @abstractmethod
    def _define_limitations(self) -> List[str]:
        """Define what this agent cannot or should not do"""
        pass
    
    @abstractmethod
    def can_handle_query(self, query: str, context: Dict[str, Any] = None) -> bool:
        """Determine if this agent can handle the given query"""
        pass
    
    @abstractmethod
    def process_query(self, query: str, context: Dict[str, Any] = None) -> AgentResponse:
        """Process the query and return response"""
        pass
    
    def validate_input(self, query: str, context: Dict[str, Any] = None) -> bool:
        """Validate input before processing"""
        if not query or not isinstance(query, str):
            return False
        
        if len(query.strip()) == 0:
            return False
        
        # Basic length check
        if len(query) > self.config.get("max_query_length", 10000):
            return False
        
        return True
    
    def update_stats(self, success: bool, execution_time: float):
        """Update agent performance statistics"""
        self.execution_stats["total_queries"] += 1
        
        if success:
            self.execution_stats["successful_queries"] += 1
        else:
            self.execution_stats["error_count"] += 1
        
        # Update average response time
        total_time = (self.execution_stats["average_response_time"] * 
                     (self.execution_stats["total_queries"] - 1) + execution_time)
        self.execution_stats["average_response_time"] = total_time / self.execution_stats["total_queries"]
    
    def get_performance_metrics(self) -> Dict[str, Any]:
        """Get agent performance metrics"""
        total = self.execution_stats["total_queries"]
        success_rate = (self.execution_stats["successful_queries"] / total * 100) if total > 0 else 0
        
        return {
            "agent_type": self.agent_type.value,
            "total_queries": total,
            "success_rate": round(success_rate, 2),
            "average_response_time": round(self.execution_stats["average_response_time"], 3),
            "error_count": self.execution_stats["error_count"],
            "capabilities": self.capabilities,
            "limitations": self.limitations
        }

class QueryAnalyzerAgent(BaseAgent):
    """Agent responsible for analyzing queries and creating execution plans"""
    
    def __init__(self, config: Dict[str, Any] = None):
        super().__init__(AgentType.QUERY_ANALYZER, config)
        
        # Query classification patterns
        self.sql_patterns = [
            r'\b(select|SELECT)\b.*\b(from|FROM)\b',
            r'\b(count|COUNT|sum|SUM|avg|AVG)\b',
            r'\bwhere\b|\bWHERE\b',
            r'\bgroup by\b|\bGROUP BY\b',
            r'\border by\b|\bORDER BY\b'
        ]
        
        self.schema_patterns = [
            r'\btable\b|\btables\b',
            r'\bcolumn\b|\bcolumns\b',
            r'\bschema\b|\bstructure\b',
            r'\brelationship\b|\bforeign key\b',
            r'\bwhat.*contain\b|\bshow.*structure\b'
        ]
        
        self.analytical_patterns = [
            r'\banalyze\b|\banalysis\b',
            r'\btrend\b|\bpattern\b',
            r'\bcompare\b|\bcomparison\b',
            r'\bsummarize\b|\bsummary\b',
            r'\binsight\b|\bfinding\b'
        ]
    
    def _define_capabilities(self) -> List[str]:
        return [
            "Query type classification",
            "Execution plan generation",
            "Agent coordination",
            "Context analysis",
            "Query decomposition"
        ]
    
    def _define_limitations(self) -> List[str]:
        return [
            "Cannot execute SQL queries",
            "Cannot access databases directly",
            "Limited to planning and coordination"
        ]
    
    def can_handle_query(self, query: str, context: Dict[str, Any] = None) -> bool:
        """Query analyzer can handle all queries for planning"""
        return True
    
    def process_query(self, query: str, context: Dict[str, Any] = None) -> AgentResponse:
        """Analyze query and create execution plan"""
        import time
        start_time = time.time()
        
        try:
            # Classify query type
            query_type = self._classify_query(query)
            
            # Generate execution plan
            plan = self._generate_execution_plan(query, query_type, context)
            
            # Determine required agents
            required_agents = self._determine_required_agents(query_type, plan)
            
            execution_time = time.time() - start_time
            self.update_stats(True, execution_time)
            
            response_content = {
                "query_plan": plan,
                "query_type": query_type,
                "required_agents": [agent.value for agent in required_agents],
                "estimated_steps": len(plan.steps),
                "complexity_score": plan.estimated_complexity
            }
            
            return AgentResponse(
                agent_type=self.agent_type,
                success=True,
                content=response_content,
                confidence=0.9,
                execution_time=execution_time,
                metadata={"classification_method": "pattern_based"}
            )
            
        except Exception as e:
            execution_time = time.time() - start_time
            self.update_stats(False, execution_time)
            
            return AgentResponse(
                agent_type=self.agent_type,
                success=False,
                content=None,
                confidence=0.0,
                execution_time=execution_time,
                metadata={},
                error_message=str(e)
            )
    
    def _classify_query(self, query: str) -> str:
        """Classify query into different types"""
        query_lower = query.lower()
        
        # Check for SQL patterns
        sql_score = sum(1 for pattern in self.sql_patterns if re.search(pattern, query, re.IGNORECASE))
        
        # Check for schema patterns  
        schema_score = sum(1 for pattern in self.schema_patterns if re.search(pattern, query, re.IGNORECASE))
        
        # Check for analytical patterns
        analytical_score = sum(1 for pattern in self.analytical_patterns if re.search(pattern, query, re.IGNORECASE))
        
        # Classification logic
        if sql_score >= 2:
            return "direct_sql"
        elif schema_score >= 1:
            return "schema_exploration"
        elif analytical_score >= 1:
            return "analytical_query"
        elif any(word in query_lower for word in ["find", "get", "show", "list", "what"]):
            return "data_retrieval"
        else:
            return "general_question"
    
    def _generate_execution_plan(self, query: str, query_type: str, context: Dict[str, Any]) -> QueryPlan:
        """Generate detailed execution plan"""
        
        steps = []
        complexity = 1
        
        if query_type == "direct_sql":
            steps = [
                {"step": 1, "action": "validate_sql_syntax", "agent": "sql_agent"},
                {"step": 2, "action": "execute_sql", "agent": "sql_agent"},
                {"step": 3, "action": "format_results", "agent": "synthesis_agent"}
            ]
            complexity = 2
            
        elif query_type == "schema_exploration":
            steps = [
                {"step": 1, "action": "search_schema", "agent": "schema_agent"},
                {"step": 2, "action": "retrieve_schema_info", "agent": "schema_agent"},
                {"step": 3, "action": "format_schema_response", "agent": "synthesis_agent"}
            ]
            complexity = 2
            
        elif query_type == "analytical_query":
            steps = [
                {"step": 1, "action": "decompose_analytical_query", "agent": "query_analyzer"},
                {"step": 2, "action": "search_relevant_data", "agent": "text_agent"},
                {"step": 3, "action": "generate_sql_if_needed", "agent": "sql_agent"},
                {"step": 4, "action": "synthesize_analysis", "agent": "synthesis_agent"}
            ]
            complexity = 4
            
        elif query_type == "data_retrieval":
            steps = [
                {"step": 1, "action": "identify_relevant_tables", "agent": "schema_agent"},
                {"step": 2, "action": "generate_retrieval_query", "agent": "sql_agent"},
                {"step": 3, "action": "execute_and_format", "agent": "synthesis_agent"}
            ]
            complexity = 3
            
        else:  # general_question
            steps = [
                {"step": 1, "action": "search_knowledge_base", "agent": "text_agent"},
                {"step": 2, "action": "generate_response", "agent": "synthesis_agent"}
            ]
            complexity = 2
        
        return QueryPlan(
            query_id=f"qplan_{hash(query) % 10000}",
            original_query=query,
            query_type=query_type,
            steps=steps,
            required_agents=self._determine_required_agents(query_type, None),
            estimated_complexity=complexity,
            context_requirements=context or {}
        )
    
    def _determine_required_agents(self, query_type: str, plan: QueryPlan) -> List[AgentType]:
        """Determine which agents are needed for execution"""
        
        agent_mapping = {
            "direct_sql": [AgentType.SQL_AGENT, AgentType.SYNTHESIS_AGENT],
            "schema_exploration": [AgentType.SCHEMA_AGENT, AgentType.SYNTHESIS_AGENT],
            "analytical_query": [AgentType.SCHEMA_AGENT, AgentType.SQL_AGENT, 
                               AgentType.TEXT_AGENT, AgentType.SYNTHESIS_AGENT],
            "data_retrieval": [AgentType.SCHEMA_AGENT, AgentType.SQL_AGENT, AgentType.SYNTHESIS_AGENT],
            "general_question": [AgentType.TEXT_AGENT, AgentType.SYNTHESIS_AGENT]
        }
        
        return agent_mapping.get(query_type, [AgentType.TEXT_AGENT, AgentType.SYNTHESIS_AGENT])

class AgentCoordinator:
    """Coordinates multiple agents for complex query processing"""
    
    def __init__(self):
        self.agents = {}
        self.message_history = []
        self.active_plans = {}
        
        logger.info("Agent coordinator initialized")
    
    def register_agent(self, agent: BaseAgent):
        """Register an agent with the coordinator"""
        self.agents[agent.agent_type] = agent
        logger.info(f"Registered agent: {agent.agent_type.value}")
    
    def process_query(self, query: str, context: Dict[str, Any] = None) -> Dict[str, Any]:
        """Coordinate agents to process complex queries"""
        
        # Step 1: Analyze query
        if AgentType.QUERY_ANALYZER not in self.agents:
            raise ValueError("Query analyzer agent not registered")
        
        analyzer = self.agents[AgentType.QUERY_ANALYZER]
        analysis_result = analyzer.process_query(query, context)
        
        if not analysis_result.success:
            return {
                "success": False,
                "error": "Query analysis failed",
                "details": analysis_result.error_message
            }
        
        # Step 2: Execute plan
        plan = analysis_result.content["query_plan"]
        required_agents = [AgentType(agent_name) for agent_name in analysis_result.content["required_agents"]]
        
        # Check if all required agents are available
        missing_agents = [agent for agent in required_agents if agent not in self.agents]
        if missing_agents:
            return {
                "success": False,
                "error": f"Missing required agents: {[a.value for a in missing_agents]}"
            }
        
        # Execute steps
        results = []
        execution_context = context or {}
        execution_context["original_query"] = query
        execution_context["query_type"] = analysis_result.content["query_type"]
        
        for step in plan.steps:
            agent_type = AgentType(step["agent"])
            agent = self.agents.get(agent_type)
            
            if agent:
                step_result = agent.process_query(query, execution_context)
                results.append({
                    "step": step["step"],
                    "action": step["action"],
                    "agent": agent_type.value,
                    "result": step_result
                })
                
                # Update context with results for next steps
                if step_result.success:
                    execution_context[f"step_{step['step']}_result"] = step_result.content
        
        # Generate final response
        final_result = self._generate_final_response(query, results, analysis_result.content)
        
        return final_result
    
    def _generate_final_response(self, query: str, step_results: List[Dict], 
                               analysis_info: Dict) -> Dict[str, Any]:
        """Generate final coordinated response"""
        
        successful_steps = [r for r in step_results if r["result"].success]
        failed_steps = [r for r in step_results if not r["result"].success]
        
        # Compile final answer
        final_content = {}
        confidence_scores = []
        
        for step_result in successful_steps:
            agent_name = step_result["agent"]
            content = step_result["result"].content
            confidence = step_result["result"].confidence
            
            final_content[f"{agent_name}_output"] = content
            confidence_scores.append(confidence)
        
        # Calculate overall confidence
        overall_confidence = sum(confidence_scores) / len(confidence_scores) if confidence_scores else 0.0
        
        return {
            "success": len(failed_steps) == 0,
            "query": query,
            "query_type": analysis_info["query_type"],
            "content": final_content,
            "confidence": overall_confidence,
            "execution_summary": {
                "total_steps": len(step_results),
                "successful_steps": len(successful_steps),
                "failed_steps": len(failed_steps),
                "complexity_score": analysis_info["complexity_score"]
            },
            "step_details": step_results,
            "metadata": {
                "processing_method": "multi_agent_coordination",
                "agents_used": list(set([r["agent"] for r in step_results]))
            }
        }
    
    def get_system_performance(self) -> Dict[str, Any]:
        """Get performance metrics for all agents"""
        return {
            "coordinator_stats": {
                "total_agents": len(self.agents),
                "active_plans": len(self.active_plans),
                "message_history_size": len(self.message_history)
            },
            "agent_performance": {
                agent_type.value: agent.get_performance_metrics() 
                for agent_type, agent in self.agents.items()
            }
        }

# Example usage and testing
if __name__ == "__main__":
    # Test query analyzer
    analyzer = QueryAnalyzerAgent()
    
    test_queries = [
        "SELECT * FROM users WHERE age > 25",
        "Show me the structure of the users table",
        "What are the trends in sales data?",
        "Find customers who made purchases last month"
    ]
    
    for query in test_queries:
        result = analyzer.process_query(query)
        print(f"\nQuery: {query}")
        print(f"Type: {result.content['query_type']}")
        print(f"Agents needed: {result.content['required_agents']}")
        print(f"Steps: {result.content['estimated_steps']}")